from enum import StrEnum


class SchemaKeyword(StrEnum):
    ADDITIONAL_PROPERTIES = "additionalProperties"
    ALL_OF = "allOf"
    ANY_OF = "anyOf"
    CONST = "const"
    CONTAINS = "contains"
    CONTENT_SCHEMA = "contentSchema"
    DEPENDENT_SCHEMAS = "dependentSchemas"
    DEPENDENT_REQUIRED = "dependentRequired"
    DEFINITIONS = "$defs"
    DESCRIPTION = "description"
    ELSE = "else"
    IF = "if"
    ITEMS = "items"
    LEGACY_DEFINITIONS = "definitions"
    MAX_ITEMS = "maxItems"
    MAX_PROPERTIES = "maxProperties"
    MIN_ITEMS = "minItems"
    MIN_PROPERTIES = "minProperties"
    NOT = "not"
    ONE_OF = "oneOf"
    PROPERTIES = "properties"
    PATTERN_PROPERTIES = "patternProperties"
    PREFIX_ITEMS = "prefixItems"
    PROPERTY_NAMES = "propertyNames"
    REFERENCE = "$ref"
    REQUIRED = "required"
    TITLE = "title"
    THEN = "then"
    TYPE = "type"
    UNEVALUATED_ITEMS = "unevaluatedItems"
    UNEVALUATED_PROPERTIES = "unevaluatedProperties"
